### PR TITLE
Enable to change state through the props

### PR DESCRIPTION
**Pull request by zoranmarjanovic**

### CODE REVIEW

**Comment by ScreamZ** [comment]
I need this too...

**Comment by jaredmahan** [comment]
Can we get this merged into master please. I need this as well.

**Comment by wbw20** [comment]
would be nice to see this merged

**Comment by wbw20** [comment]
@crazycodeboy I'll venmo you $20 to look at this PR 😂

**Comment by flyingxu** [comment]
I must be crazy but I modified the source code myself locally.

**Comment by sjsn** [comment]
+1

**Comment by ScreamZ** [comment]
@crazycodeboy Can we get this merged please ?

**Comment by ScreamZ** [comment]
Finally, thank you

**Pull request merged**
