### PR TITLE
Updated checkbox state when isChecked in props is changed

### PR DESCRIPTION
**Pull request by Kameshwaran**
### This PR fixes issue #48

### CODE REVIEW

**Comment by Kameshwaran** [comment]
@crazycodeboy can you please merge this quickly?

**Comment by cereigido** [comment]
@crazycodeboy, I'm also using this PR version. Please merge it.

**Comment by derekbrown** [comment]
@crazycodeboy Please merge.

**Comment by andrefarzat** [comment]
@crazycodeboy Please merge.

**Comment by crazycodeboy** [comment]
merged to  [v2.1.0](https://github.com/crazycodeboy/react-native-check-box/)

**Comment by xufeipyxis** [comment]
I'm afraid it's still not working at v2.1.0

**Pull request closed without merging**
